export const SET_ITEMS = 'POST/SET_ITEMS';
export const FETCH_DATA_ASYNC = 'POST/FETCH_DATA_ASYNC';
export const SET_COMMENTS = 'POST/SET_COMMENTS';
export const ADD_ITEM = 'POST/ADD_ITEM';
export const UPDATE_ITEMS = 'POST/UPDATE_ITEMS';
export const DELETE_ITEM = 'POST/DELETE_ITEM';
export const UPDATE_COMMENT = 'POST/UPDATE_COMMENT';
export const INIT_ITEMS = 'POST/INIT_ITEMS';